config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :wine_strains
  resources :strains
  resources :wines
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "wines#index"
end

app/models/wine_strain.rb
class WineStrain < ApplicationRecord
  belongs_to :wine
  belongs_to :strain
end

app/controllers/wine_strains_controller.rb
class WineStrainsController < ApplicationController
  before_action :set_wine_strain, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :auth_user

  # GET /wine_strains or /wine_strains.json
  def index
    @wine_strains = WineStrain.all
  end

  # GET /wine_strains/1 or /wine_strains/1.json
  def show
  end

  # GET /wine_strains/new
  def new
    @wine_strain = WineStrain.new
  end

  # GET /wine_strains/1/edit
  def edit
  end

  # POST /wine_strains or /wine_strains.json
  def create
    @wine_strain = WineStrain.new(wine_strain_params)

    respond_to do |format|
      if @wine_strain.save
        format.html { redirect_to wine_strain_url(@wine_strain), notice: "Wine strain was successfully created." }
        format.json { render :show, status: :created, location: @wine_strain }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine_strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wine_strains/1 or /wine_strains/1.json
  def update
    respond_to do |format|
      if @wine_strain.update(wine_strain_params)
        format.html { redirect_to wine_strain_url(@wine_strain), notice: "Wine strain was successfully updated." }
        format.json { render :show, status: :ok, location: @wine_strain }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine_strain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wine_strains/1 or /wine_strains/1.json
  def destroy
    @wine_strain.destroy

    respond_to do |format|
      format.html { redirect_to wine_strains_url, notice: "Wine strain was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine_strain
      @wine_strain = WineStrain.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_strain_params
      params.require(:wine_strain).permit(:wine_id, :strain_id, :percentage)
    end

    def auth_user
      unless current_user.roles.pluck(:name) == ["admin"]
    redirect_to root_path
      end
  end
end

app/helpers/wine_strains_helper.rb
module WineStrainsHelper
end

app/views/wine_strains/_form.html.erb
<%= form_with(model: wine_strain) do |form| %>
  <% if wine_strain.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wine_strain.errors.count, "error") %> prohibited this wine_strain from being saved:</h2>

      <ul>
        <% wine_strain.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :wine_id, style: "display: block" %>
    <%= form.text_field :wine_id %>
  </div>

  <div>
    <%= form.label :strain_id, style: "display: block" %>
    <%= form.text_field :strain_id %>
  </div>

  <div>
    <%= form.label :percentage, style: "display: block" %>
    <%= form.number_field :percentage %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wine_strains/_wine_strain.html.erb
<div id="<%= dom_id wine_strain %>">
  <p>
    <strong>Wine:</strong>
    <%= wine_strain.wine_id %>
  </p>

  <p>
    <strong>Strain:</strong>
    <%= wine_strain.strain_id %>
  </p>

  <p>
    <strong>Percentage:</strong>
    <%= wine_strain.percentage %>
  </p>

</div>

app/views/wine_strains/edit.html.erb
<h1>Editing wine strain</h1>

<%= render "form", wine_strain: @wine_strain %>

<br>

<div>
  <%= link_to "Show this wine strain", @wine_strain %> |
  <%= link_to "Back to wine strains", wine_strains_path %>
</div>

app/views/wine_strains/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wine strains</h1>

<div id="wine_strains">
  <% @wine_strains.each do |wine_strain| %>
    <%= render wine_strain %>
    <p>
      <%= link_to "Show this wine strain", wine_strain %>
    </p>
  <% end %>
</div>

<%= link_to "New wine strain", new_wine_strain_path %>

app/views/wine_strains/new.html.erb
<h1>New wine strain</h1>

<%= render "form", wine_strain: @wine_strain %>

<br>

<div>
  <%= link_to "Back to wine strains", wine_strains_path %>
</div>

app/views/wine_strains/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wine_strain %>

<div>
  <%= link_to "Edit this wine strain", edit_wine_strain_path(@wine_strain) %> |
  <%= link_to "Back to wine strains", wine_strains_path %>

  <%= button_to "Destroy this wine strain", @wine_strain, method: :delete %>
</div>