config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :wine_strains
  resources :strains
  resources :wines
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root to: "wines#index"
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_strains, dependent: :destroy
    has_many :strains, through: :wine_strains
    has_one_attached :avatar
    accepts_nested_attributes_for :wine_strains, reject_if: :all_blank, allow_destroy: true

    def addStrainPercentage(percentages)
        percentages.each do |strain_id, percentage|
            if percentage != ""
                temp_strain = self.wine_strains.where(strain_id: strain_id.to_i).first
                temp_strain.percentage = percentage.to_i
                temp_strain.save
            end
        end
    end

    def getPercentageByStrainId(strain_id)
        if self.wine_strains.where(strain_id: strain_id.to_i).first
            self.wine_strains.where(strain_id: strain_id.to_i).first.percentage
        end
    end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :set_wine, only: %i[ show edit update destroy ]
  before_action :only_strains_availables, only: %i[ new edit ]
  # GET /wines or /wines.json
  def index
    @wines = Wine.eager_load(:strain)
    @wines = Wine.all
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
  end

  # GET /wines/1/edit
  def edit
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        @wine.addStrainPercentage(params[:wine][:strains_percentage])
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        @wine.addStrainPercentage(params[:wine][:strains_percentage])
        format.html { redirect_to wine_url(@wine), notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy

    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, :score, :avatar, { strain_ids: [] })
    end

    def only_strains_availables
      @strains_availables = Strain.where(available: true)
    end
end

app/helpers/wines_helper.rb
module WinesHelper
end

app/views/wines/_form.html.erb
<%= form_with(model: wine) do |form| %>
  <% if wine.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
        <% wine.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :score, style: "display: block" %>
    <%= form.number_field :score %>
  </div>

  <div>
    <%= form.label :strains %> <br />
    <%= form.collection_check_boxes(:strain_ids, @strains_availables, :id, :name) do |b| %>
      <%= b.label class: "label_checkbox" do %>
        <%= b.check_box + b.text %>
        <%= text_field("wine[strains_percentage]", b.value, value:@wine.getPercentageByStrainId(b.value)) %>
      <% end %>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/wines/_wine.html.erb
<div id="<%= dom_id wine %>">
  <p>
    <strong>Name:</strong>
    <%= wine.name %>
  </p>

  <p>
    <strong>Score:</strong>
    <%= wine.score %>
  </p>

  <p>
    <strong>Strains:</strong>
    <%= wine.strains.order(:name).map{ |s| "#{s.name} - (#{wine.getPercentageByStrainId(s.id)}%)"}.sort.join(' , ') %>

  </p>
</div>

app/views/wines/edit.html.erb
<h1>Editing wine</h1>

<%= render "form", wine: @wine %>

<br>

<div>
  <%= link_to "Show this wine", @wine %> |
  <%= link_to "Back to wines", wines_path %>
</div>

app/views/wines/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Wines</h1>

<div id="wines">
  <% @wines.each do |wine| %>
    <%= render wine %>
    
     <% if current_user %>
    <p>
      <%= link_to "Show this wine", wine %>
    </p>
      <% end %>
  <% end %>
</div>


<% if current_user %>
<%= link_to "New wine", new_wine_path %>
<% end %>

app/views/wines/new.html.erb
<h1>New wine</h1>

<%= render "form", wine: @wine %>

<br>

<div>
  <%= link_to "Back to wines", wines_path %>
</div>

app/views/wines/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @wine %>
  
<div>
  <%= link_to "Edit this wine", edit_wine_path(@wine) %> |
  <%= link_to "Back to wines", wines_path %>

  <%= button_to "Destroy this wine", @wine, method: :delete %>
</div>